### ISSUE TITLE
Add some meta commands to the CLI

### ISSUE THREAD

**Issue by geoffdavis92** [knicklabs/lorem-ipsum.js#12]
It would be nice to have some commands to view the syntax/commands and the version via the CLI.

``` bash
$ lorem-ipsum -v [--version]
$ lorem-ipsum help [-h [ --help]]
```

Just a thought as I updated my local package.

Thanks!

**Comment by knicklabs** [comment]
Thanks for the suggestion. This is a great idea and I'll plan to include it in a future release.

**Comment by knicklabs** [comment]
This feature is included in version 2. See https://github.com/knicklabs/lorem-ipsum.js/pull/27.
