### ISSUE TITLE
Option --copy doesnt copy to clipboard

### ISSUE THREAD

**Issue by gabrielps** [knicklabs/lorem-ipsum.js#13]
Hi there!
When writing ie
`lorem-ipsum 1 sentence --copy`, the clipboard remains with the previous content, not the generated sentence.

I'm on Ubuntu 16.04

**Comment by knicklabs** [comment]
@gabrielps Do you have xclip installed? If not, what command do you use to copy to the clipboard from your terminal?

**Comment by knicklabs** [comment]
As mentioned in the README, Linux support requires xclip to be installed. On Ubuntu, you can install it with `apt-get install xclip`. Unfortunately, this doesn't work with headless servers. See: http://stackoverflow.com/questions/18695934/error-cant-open-display-null-when-using-xclip-to-copy-ssh-public-key.

If you still have issues (or you have any ideas about how to get around the limitation with headless servers) I'd appreciate hearing about them. Let me know and we can revisit opening this issue if necessary. Thanks!
