### ISSUE TITLE
Adding RTL mode

### ISSUE THREAD

**Issue by joscha** [knicklabs/lorem-ipsum.js#14]
Would you accept a PR that allows us to kick the generator into RTL mode and change the default text from English lipsum to arabic or hebrew (see http://generator.lorem-ipsum.info/_arabic).
Currently, we could only do this with a wrapping script, providing a different wordlist, but testing components in RTL is something that would be great if it came OOTB.

**Comment by knicklabs** [comment]
Hey @joscha! Absolutely, would accept a PR for that.

**Comment by knicklabs** [comment]
Closing as it is not something on my radar to add, but if you want to submit a PR I would be happy to accept it. Cheers.
