### ISSUE TITLE
ES6 syntax

### ISSUE THREAD

**Issue by marcobiedermann** [knicklabs/lorem-ipsum.js#18]
Hey Nickolas great library of yours.
I would like to use it in my project in which I use ES6 syntax.
How about giving your code a little ES6 upgrade? Makes the code a bit cleaner in some ways.
Currently most features are supported in Node.js 4+

I would like to use:
* `let` and `const` instead of `var`
* template strings to make string concatenation easier to read and write
* `Object.assign` to make default options more easy to set up

Optional:
* use `import` and `export` to support official JavaScript modules.

If you like, I could work on that and send you a PR.

**Comment by knicklabs** [comment]
I don't have bandwidth to upgrade to ES6 and this time and you should be fine to use the package in your ES6 projects just fine. If you want to submit a PR that's awesome and I'd be happy to have you contribute! I'll re-open the issue if you do but for now I'm going to close it. Will reconsider if I find some time to work on it. Thanks.

**Comment by MehbubRashid** [comment]
Hi, @knicklabs i am wondering how this library works both with import and require syntax?i want to make a library which both supports in browser,require and import.can you please tell?
