### ISSUE TITLE
Can I use this module in my Alfred workflow?

### ISSUE THREAD

**Issue by AntonNiklasson** [knicklabs/lorem-ipsum.js#19]
I wrote a tiny Alfred workflow to grab some lorem ipsum text quickly using this module. Are you fine with that? I can add something in the readme, like your name and an email or something?

[github.com/AntonNiklasson/alfred-loremipsum](http://www.github.com/AntonNiklasson/alfred-loremipsum)

**Comment by knicklabs** [comment]
Very cool! Thanks for sharing :)

There's no need for attribution.
