### ISSUE TITLE
Package size skyrocketed between 1.x and 2.x versions

### ISSUE THREAD

**Issue by dubzzz** [knicklabs/lorem-ipsum.js#30]
Both [bundlephobia](https://bundlephobia.com/result?p=lorem-ipsum@2.0.0-alpha.2) and [npm-download-size](https://arve0.github.io/npm-download-size/#lorem-ipsum@2.0.0-alpha.2) agree on the fact that the size of the npm package skyrocketed with the current alpha.

According to npm-download-size:
- https://arve0.github.io/npm-download-size/#lorem-ipsum@2.0.0-alpha.2 - 42.8KiB for a total size of 93.9KiB
- https://arve0.github.io/npm-download-size/#lorem-ipsum@1.0.6 - 4.9KiB for a total size of 12.4KiB

No problem on my side but I think it might be an issue for users serving web-content relying on this library.

**Comment by knicklabs** [comment]
There are three reasons for the bloat:

1. I introduced an undocumented `seed` option which used a new `random-seed` package
2. I replaced `minimist` with the larger but supported `commander` package
3. I switched to Typescript and the code is transpiled now and as a result not quite as a lean. 

I removed the `seed` option and the `random-seed` package. If users want that feature, they can supply their own seeded PRNG function via the `random` option. 

That brings the package size down to 31.28kb. The commander dependency accounts for 17.9K of that and that does not get shipped to the browser. So we're shipping 13k to the browser. Sure it's a 3x increase, but gzipped, it will be negligible.
