### ISSUE TITLE
React Native: Unable to resolve module `child_process`

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [knicklabs/lorem-ipsum.js#33]
Hi

I'm trying to install lorem-ipsum in my react-native project, but I'm getting the following error from my bundler:
> error: bundling failed: Error: Unable to resolve module `child_process` from `/Users/jenskuhrjorgensen/Documents/Workspace/journl-incontinence/mobile/node_modules/lorem-ipsum/dist/index.js`: Module `child_process` does not exist in the Haste module map

I've tried to restart the metro bundler with `npm run start -- --reset-cache` and remove and re-install node_modules, but to no avail. 

Any help would be appreciated! :)

Environment:
"react": "16.6.3"
"react-native": "0.58.5"
"lorem-ipsum": "2.0.0-alpha.7"

**Comment by knicklabs** [comment]
Until this issue is resolved, is it possible to downgrade to 1.0.6. It's functionally the same.

**Comment by knicklabs** [comment]
Just wanted to follow-up to say that I looked into this issue and it seems to be a problem with React Native. See here for some discussion https://github.com/ethers-io/ethers.js/issues/268

That said, there was an issue with the builds where code meant to be executed in a server context (as part of the included CLI) was being included in the client libraries. That's sorted out now. I don't have a React Native project to test this with, but it *should* work now after the updates in https://github.com/knicklabs/lorem-ipsum.js/pull/34.

**Comment by karolis-adapt** [comment]
@knicklabs I get the same error in a project that's rendered server-side -- so not strictly React Native. Not sure if it matters much, but the rendering is handled by [`razzle`](https://github.com/jaredpalmer/razzle)

**Comment by knicklabs** [comment]
Hi @karolis-adapt, are you using the alpha version (v2.0.0-alpha.x) or version the latest stable release (v2.0.0)

**Comment by karolis-adapt** [comment]
@knicklabs was running latest stable. Figured task being closed meant it's released. If the fix is only in alpha, then pay no attention to my earlier comment ;)

**Comment by knicklabs** [comment]
This fix should be in version 2.0.0. Will investigate further, thanks. The child process module should only be imported in the executable script for the command line program. I'll investigate further.

**Comment by nocarroll** [comment]
I'm getting the same error in a webpack build with 2.0.0.

The error was happening with 1.0.6 as well but adding `browser: { child_process: false }` to package.json fixed it. The same fix doesn't have any effect in 2.0.0

**Comment by knicklabs** [comment]
@nocarroll Thanks for letting me know what you were seeing. That helped track down the issue.
