### ISSUE TITLE
Error to import lorem-ipsum in typescript

### ISSUE THREAD

**Issue by dancespiele** [knicklabs/lorem-ipsum.js#39]
**Describe the bug**
I get this error when I import the module:

```
/home/spielrs/Proyectos/quarantine-digest/node_modules/lorem-ipsum/src/index.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { WORDS } from "./constants/words";
                                                                                                    ^

    SyntaxError: Unexpected token {

      1 | import * as moment from "moment";
      2 | import {IFeed} from "./interfaces";
    > 3 | import {LoremIpsum} from "lorem-ipsum/src";
        | ^
      4 | 
      5 | const emails: IFeed[] = [];
      6 | 

```

**To Reproduce**
import lorem-ipsum with typescript

```typescript
import {LoremIpsum} from "lorem-ipsum/src";
```
**Expected behavior**
1. I shouldn't add `src` to the import path to get the types
2. I shouldn't get the error when I import it

**Desktop (please complete the following information):**
 - OS: Solus

**Comment by vladkasianenko** [comment]
I have the same problem. Try installing just `lorem-ipsum` and then Visual Studio Code should suggest you installing types from `@types/lorem-ipsum`. After that `import { loremIpsum } from 'lorem-ipsum'` is not working, however `import { loremIpsum } from 'lorem-ipsum/src'` is OK.

**Comment by knicklabs** [comment]
Hi @dancespiele, agreed you should not have to import from `/src` to get types and it looks like the other error you are experiencing stems from that. The path for types in the module's package.json file is incorrect. I'll get that fixed up shortly and make a new release. Thanks for bringing the issue to my attention.

**Comment by knicklabs** [comment]
@dancespiele I've pushed out a fix for this issue. See version 2.0.2. You can now `import { LoremIpsum } from 'lorem-ipsum` and you'll get the types.

@vladkasianenko this should address the issue you were running into as well. This package does include types but the path was incorrect. All fixed up now. By the way, @types/lorem-ipsum is for version 1 of this library. No need to use the definitely typed definitions for version 2.
