### ISSUE TITLE
Property 'platform' does not exist on type 'Process'

### ISSUE THREAD

**Issue by averageflow** [knicklabs/lorem-ipsum.js#51]
**Describe the bug**
It is great that the project is fully TypeScript. The only problem is when you use globals like process. That can backfire on you. My projects use strict: true and won't build because of this type error. I have had to resort to a @ts-ignore. 

```
ERROR in /Users/joe/workspace/site_ui_components_v2/node_modules/lorem-ipsum/src/util/isWindows.ts(7,52):
7:52 Property 'platform' does not exist on type 'Process'.
     5 |  */
     6 | const isWindows = (): boolean => {
  >  7 |   return typeof process !== "undefined" && process.platform === SUPPORTED_PLATFORMS.WIN32;
       |                                                    ^
     8 | };
     9 | 
    10 | export default isWindows;
Version: typescript 3.9.7
```

**To Reproduce**
This error occurs with `npm run serve`  or  `npm run start` (dev server) and with `npm run build`

**Expected behavior**
No type errors.

**Screenshots**
![Screenshot 2020-09-04 at 10 20 46](https://user-images.githubusercontent.com/42377845/92218244-1b152900-ee99-11ea-866e-4d082dd464eb.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6 & Ubuntu 18.04

**Comment by knicklabs** [comment]
This is resolved with #52.
