### ISSUE TITLE
Circular dependency detected sees cyclic dependency in util/makeArrayOfStrings.js and util/index.js

### ISSUE THREAD

**Issue by saschati** [knicklabs/lorem-ipsum.js#68]
I use `CircularDependencyPlugin` to find cyclic modules in my projects, and when using the `lorem-ipsum` webpack plugin sees the following cyclic dependency:
```
WARNING in Circular dependency detected:
node_modules/lorem-ipsum/dist/util/index.js -> node_modules/lorem-ipsum/dist/util/makeArrayOfStrings.js -> node_modules/lorem-ipsum/dist/util/index.js

WARNING in Circular dependency detected:
node_modules/lorem-ipsum/dist/util/makeArrayOfStrings.js -> node_modules/lorem-ipsum/dist/util/index.js -> node_modules/lorem-ipsum/dist/util/makeArrayOfStrings.js
```

**To Reproduce**
1. Install `circular-dependency-plugin:^5.2.2`
2. Install `lorem-ipsum:^2.0.4`
3. Use `lorem-ipsum` class or function
4. See warning

**Expected behavior**
It seems to me that there should be no cyclic modules, but I do not know how critical it is in this case and whether I should ignore this warning.

**Screenshots**
https://i.imgur.com/greWD4u.png

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - webpack: `webpack:^5.72.1`
 - webpack-cli: `webpack-cli:^4.9.2`
 - lorem-ipsum: `lorem-ipsum:^2.0.4`
 - CircularDependencyPlugin: `circular-dependency-plugin:^5.2.2`

**Smartphone (please complete the following information):**
none

**Additional context**
none

**Comment by knicklabs** [comment]
Hi @saschati! Thanks for filing such a detailed report about this issue. Happy to report that it was resolved by https://github.com/knicklabs/lorem-ipsum.js/pull/65. Updating to the latest release (2.0.8) should resolve this issue for you. Cheers!
