### ISSUE TITLE
Don't print carriage returns on linux / Don't print newlines on os x

### ISSUE THREAD

**Issue by johanhelsing** [knicklabs/lorem-ipsum.js#7]
The tool always prints \r\n at new lines. It would be nice if the tool adapted to the current platform or if the end-of-line was configurable.

https://github.com/knicklabs/lorem-ipsum.js/blob/master/lib/generator.js#L61

**Comment by knicklabs** [comment]
Thanks for the pull request which addressed this issue. It has been merged into the latest version.
